# Generated by Django 5.2 on 2025-04-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
